package cl.ufro.dci.ed.model;

public enum Posicion {
    PORTERO,DEFENSA,LATERAL,
    MEDIOCAMPISTA_DEFENSIVO,MEDIOCAMPISTA_CENTRAL,MEDIOCAMPISTA_OFENSIVO,
    DELANTERO_CENTRO,MEDIAPUNTA,EXTREMO_DERECHO,EXTREMO_IZQUIERDO;
}
